### ISSUE TITLE
keyboard input monitoring stops working periodically

### ISSUE THREAD

**Issue by craigfurman** [ohueter/autokbisw#47]
Hi, firstly: thanks for maintaining this program, it's super useful. Second: this is going to be a rather vague bug report and I apologise for that in advance. Please let me know if there is any more diagnostic information that might come in handy.

Sometimes, after my host laptop from sleep, autokbisw just stops working. I think it's not receiving keystroke events, according to the following experiment:

1. `launchctl unload` the plist
2. validate that the process is no longer running: `ps -ef | grep autokbisw`
3. Validate that autokbisw is allowed to monitor keyboard input in macos settings
   1. My terminal is also permitted to monitor keyboard input. I believe that mac's permission model requires this to perform the next test, which is executing autokbisw from a shell.
5. `autokbisw -v 2`
6. Press some buttons on either my external keyboard or my macbook's builtin keyboard
7. See nothing in the output
8. Input switching does not work
This is in contrast to periods in which autokbisw does appear to work (again, apologies for the vague language here), when `autokbisw -v 2` shows events for every keypress.

I've tried `autokbisw clear` when the program is not running, and rebooting, but I can't find a clear proximate cause yet.

One other breadcrumb is that I regularly disconnect and reconnect the external keyboard (via a USB hub) before or shortly after sleeping the laptop, and reattaching it after wake.

When the issue occurs, the only somewhat-reliable way I've found so far to work around it is to reboot with the external keyboard still plugged in.

**Comment by craigfurman** [comment]
It's _possible_ I have rubber-ducked this within minutes of opening the issue, but I won't be sure until I've had a few days to validate that the fix holds. I think I had a corrupted `defaults` for autokbisw. According to `defaults read autokbisw`, as well as my 2 keyboards, I had an entry under keyboardISMapping whose _key_ was the empty string.

I stopped the service, then ran `autokbisw clear`, ran `defaults delete autokbisw`, then rebooted, and things appear healthier now. There is no empty string in autokbisw's defaults.

**Comment by ohueter** [comment]
Hi Craig, thanks for the detailed report!

It's hard to debug what's causing this. I often see similar behavior after developing on autokbisw, especially after removing and re-installing the service via `brew`. Maybe the HIDManager callback is lost (which IMO should be resolved by restarting the program), or it's a permissions issue (which I think is more likely). There's definitely something happening that I don't fully understand at the moment.

Please report back if your issue was permanently resolved just be clearing the defaults!

Always happy to assist in more rubber-ducking :-)

**Comment by craigfurman** [comment]
I was too optimistic - the issue has reoccured. After waking the laptop from sleep and plugging in my USB hub, autokbisw has stopped working.

Interestingly, `autokbisw list` appears to be "frozen" to one keyboard layout for both keyboards even as I manually switch between my 2 keyboard layouts ("British" and "British PC"):

```
$ autokbisw list
1. Apple Internal Keyboard / Trackpad-[1452-641-Apple Inc.-FM714740HG3N4FTBE+FCM]: enabled - British – PC (com.apple.keylayout.British-PC)
2. USB Keyboard-[1241-17733-unknown-unknown]: enabled - British – PC (com.apple.keylayout.British-PC)
```

The defaults no longer have that empty string value:

```
$ defaults read autokbisw
{
    keyboardISMapping =     {
        "Apple Internal Keyboard / Trackpad-[1452-641-Apple Inc.-FM714740HG3N4FTBE+FCM]" = "com.apple.keylayout.British-PC";
        "USB Keyboard-[1241-17733-unknown-unknown]" = "com.apple.keylayout.British-PC";
    };
    mappingEnabled =     {
        "Apple Internal Keyboard / Trackpad-[1452-641-Apple Inc.-FM714740HG3N4FTBE+FCM]" = 1;
        "USB Keyboard-[1241-17733-unknown-unknown]" = 1;
    };
}
```

This behaviour persists across a service restart.

I should note that I'm not actually using the homebrew service anymore - I recently switched from homebrew to nix-darwin, and have packaged autokbisw for nix (but not submitted it upstream yet): https://github.com/craigfurman/nix-workstations/blob/main/pkgs/autokbisw/default.nix

I _think_ I was seeing this behaviour before I made the switch recently, but I'll try switch back to homebrew's autokbisw package and service in case that makes a difference.

**Comment by craigfurman** [comment]
I stopped my nix-darwin-managed service, reinstalled the homebrew version and service, gave the homebrew binary permissions to monitor keyboard when prompted, then restarted the homebrew service and validated that only the brew version was running.

The "frozen list" symptom I described above still occurs.

**Comment by ohueter** [comment]
I can reproduce the issue just be unplugging my USB keyboard and then plugging in again. Events from this device are not detected anymore.

Would you mind testing the version from this branch containing a fix that restarts keyboard event monitoring after USB device changes (also sleep/wake cycles, but this doesn't seem to be necessary) are detected:
 https://github.com/ohueter/autokbisw/tree/fix/events-not-detected-from-device-after-re-plugging

It contains verbose logging in debug level, so running with `-v 1` is enough to see whats going on. Thanks a lot!

**Comment by craigfurman** [comment]
I just built and tried this (just running from a shell rather than a service), and after successfully handling a few keystroke events it "locked up" and appeared to stop receiving keystroke events. I hadn't toggled sleep / unplugged a keyboard. Logs:

```
$ ./.build/release/autokbisw -v 1                      
Starting with useLocation: false - verbosity: 1
Failed to open HID Manager: -536870174
Currently connected HID devices: 3
Starting system event observation
Successfully registered for USB notification type: IOServicePublish
USB device change detected
USB device event for: USB Billboard Device   
USB device event for: USB Keyboard
USB device event for: USB 10/100/1000 LAN
USB device event for: USB2.0 Hub
USB device event for: USB Receiver
USB device event for: USB3.1 Hub
USB device event for: USB 2.0 BILLBOARD
USB device event for: USB3.0 Hub             
USB device event for: USB2.0 Hub             
Successfully registered for USB notification type: IOServiceTerminate
USB device change detected
Successfully registered for USB notification type: IOServiceMatched
USB device change detected
USB device event for: USB Billboard Device   
USB device event for: USB Keyboard
USB device event for: USB 10/100/1000 LAN
USB device event for: USB2.0 Hub
USB device event for: USB Receiver
USB device event for: USB3.1 Hub
USB device event for: USB 2.0 BILLBOARD
USB device event for: USB3.0 Hub             
USB device event for: USB2.0 Hub             
Restarting monitoring...
Monitoring restarted
Failed to open HID Manager: -536870174
Currently connected HID devices: 3
```

That "Failed to open HID Manager: -536870174" looks like a potential proximate cause, although I'm not familiar with this area.

Googling that error code, it appears to be a permission error. Both this build of autokbisw and my terminals (I've tried a couple of terminals for this) have keyboard input monitoring permission. I'm not using karabiner or anything similar:

<img width="702" alt="Image" src="https://github.com/user-attachments/assets/ec6d3db8-52a1-4246-88af-670ba6fc67c1" />

**Comment by ohueter** [comment]
Yes this is `kIOReturnNotPermitted` which means permissions for input monitoring are missing. When started directly from Terminal, granting permissions to Terminal should be enough. I'm not sure this is related to your initial issue. Maybe removing all instances of autokbisw and Terminal from System settings and rebooting helps to make a fresh start?

**Comment by ohueter** [comment]
It would be interesting to know if clearing and re-granting permissions resolves your latest issue. I noticed the error occurs right after startup:

```
$ ./.build/release/autokbisw -v 1                      
Starting with useLocation: false - verbosity: 1
Failed to open HID Manager: -536870174
```

Apart from that I pushed a new version that embeds a bundle identifier into the binary. This supposedly helps with permission issues. Maybe you could try that version as well: https://github.com/ohueter/autokbisw/pull/48

**Comment by craigfurman** [comment]
I just tried the latest build from your PR, and the same sort of behaviour occurs:

```
$ ./.build/release/autokbisw -v 1
Starting with useLocation: false - verbosity: 1
Failed to open HID Manager: -536870174
Currently connected HID devices: 4
Starting system event observation
Successfully registered for USB notification type: IOServicePublish
USB device change detected
USB device event for: USB Billboard Device   
USB device event for: USB 2.0 BILLBOARD             
USB device event for: USB Keyboard
USB device event for: USB 10/100/1000 LAN
USB device event for: USB Receiver
USB device event for: USB3.0 Hub             
USB device event for: USB2.0 Hub             
Successfully registered for USB notification type: IOServiceTerminate
USB device change detected
Successfully registered for USB notification type: IOServiceMatched
USB device change detected
USB device event for: USB Billboard Device   
USB device event for: USB 2.0 BILLBOARD             
USB device event for: USB Keyboard
USB device event for: USB 10/100/1000 LAN
USB device event for: USB Receiver
USB device event for: USB3.0 Hub             
USB device event for: USB2.0 Hub             
Restarting monitoring...
Monitoring restarted
Failed to open HID Manager: -536870174
Currently connected HID devices: 4
```

It prints those log lines, and subsequent keypresses do not result in more verbose logging. The application seems to not be monitoring keyboard input. I'll try that reboot now and will report back.

**Comment by craigfurman** [comment]
After removing all autokibsw input monitoring permissions, rebooting, reconfiguring those permissions, then restarting the service,  v2.0.1 began working. I then began experiments involving unplugging and re-plugging the keyboard and sleeping the laptop. Unplugging the keyboard, sleeping, waking, then replugging the keyboard reproduced the issue, in which autokbisw no longer responds to events. This persists even after restarting the launchd service.

**Comment by ohueter** [comment]
Ok I pushed one more code change to #48. Could you try to compile from the branch, get the permissions working, and then do a fresh start with logging (`./.build/release/autokbisw -v 1`), just do the minimum actions to reproduce the issue (press one key on each keyboard so we see the switching work, unplug, sleep, replug, type, etc), and post the log here? Which Macbook and macOS version are you using?

If we don't get a hint from this, I'm mostly out of ideas what else we might try to debug ...

**Comment by craigfurman** [comment]
No luck from the latest build unfortunately:

```
$ ./.build/release/autokbisw -v 1
Starting with useLocation: false - verbosity: 1
Failed to open HID Manager: -536870174
Starting system event observation
Successfully registered for USB notification type: IOServicePublish
USB device change detected
USB device event for: USB Billboard Device   
USB device event for: USB 2.0 BILLBOARD             
USB device event for: USB Keyboard
USB device event for: USB 10/100/1000 LAN
USB device event for: USB Receiver
USB device event for: USB2.0 Hub             
USB device event for: USB3.0 Hub             
Successfully registered for USB notification type: IOServiceTerminate
USB device change detected
Successfully registered for USB notification type: IOServiceMatched
USB device change detected
USB device event for: USB Billboard Device   
USB device event for: USB 2.0 BILLBOARD             
USB device event for: USB Keyboard
USB device event for: USB 10/100/1000 LAN
USB device event for: USB Receiver
USB device event for: USB2.0 Hub             
USB device event for: USB3.0 Hub             
Failed to open HID Manager: -536870174
Restarting monitoring...
Monitoring restarted
Failed to open HID Manager: -536870174
Failed to open HID Manager: -536870174
Failed to open HID Manager: -536870174
Failed to open HID Manager: -536870174
Failed to open HID Manager: -536870174
Failed to open HID Manager: -536870174
Failed to open HID Manager: -536870174
Failed to open HID Manager: -536870174
Failed to open HID Manager: -536870174
Failed to open HID Manager: -536870174
Failed to open HID Manager: -536870174
```

It logs that last line every second or so.

I know what you mean about running out of ideas 😁 
Presumably this can't be affecting most users otherwise we'd have more issues open here?

re: macos version: Macbook air M1, macOS 15.2. I actually have another macbook that I experience this problem on: an M3 macbook pro, same macOS version.

One final breadcrumb that just occurred to me: I'm not running any software that interferes with the keyboard drivers (as far as I know at least), but I _am_ running Logitech Options, for my wireless mouse. My keyboards are not logitech (I know there's a note about logitech in the README), they are both Filco Majestouch Tenkeyless (one v2, one v3). They're both wired USB keyboards.

**Comment by ohueter** [comment]
I'm confused, can you get the version compiled from #48 working at all? From your logs it seems like permissions are missing right from startup, and autokbisw doesn't do anything, as one would expect ...

> ```
> $ ./.build/release/autokbisw -v 1
> Starting with useLocation: false - verbosity: 1
> Failed to open HID Manager: -536870174
> ```

Is this still related to your initial issue with recovery from re-pugging and sleep/wake cycles?
Can you make sure there's only a single instance of autokbisw running: the one started manually, and no Brew/Nix service?

For reference, here's what I'm seeing on my system (M3, macOS 14.4):

```
$ ./.build/release/autokbisw -v 1
Starting with useLocation: false - verbosity: 1
HID Manager opened successfully
Currently connected HID devices: 4

... device list etc, then why i type:

change: keyboard changed from nil to Apple Keyboard-[1452-591-Apple Inc.-unknown]
Setting input source for keyboard Apple Keyboard-[1452-591-Apple Inc.-unknown]: <TSMInputSource 0x600003b4a7e0> KB Layout: U.S. (id=0)
change: keyboard changed from Apple Keyboard-[1452-591-Apple Inc.-unknown] to Apple Keyboard-[1452-592-Apple Inc.-unknown]
Setting input source for keyboard Apple Keyboard-[1452-592-Apple Inc.-unknown]: <TSMInputSource 0x600003b4a820> KB Layout: German (id=3)

... more logging, then a sleep / wake cycle: 

System woke from sleep, restarting monitoring
Restarting monitoring...
HID Manager closed successfully
Monitoring restarted
HID Manager opened successfully
```

Monitoring survives all unplugging (only keyboard and USB hub with connected keyboards) and sleeping / waking ...

To me, it seems like there's a root issue with permissions on your system that needs to be resolved first ...
Maybe by clearing TCC permissions from the command line: `tccutil reset InputMonitoring` (followed by rebooting), or forcefully deleting the TCC database at `/Library/Application Support/com.apple.TCC/TCC.db` (I have no idea what happens then, keep a backup please).

**Comment by craigfurman** [comment]
> From your logs it seems like permissions are missing right from startup

Ah yes, that does appear to be correct.

> Can you make sure there's only a single instance of autokbisw running: the one started manually, and no Brew/Nix service?

Yep, in all experiments reported here, I grepped the process table before running the branch build.

I (re)configured input monitor for another terminal (Terminal.app) and ran the latest build from there. At first, we get further - it works, even across a keyboard replug. But not across a sleep-and-wake:

```
$ ./.build/release/autokbisw -v 1
Starting with useLocation: false - verbosity: 1
HID Manager opened successfully
Currently connected HID devices: 3
Found HID device: USB Receiver
Found HID device: Apple Internal Keyboard / Trackpad
Found HID device: USB Keyboard
Starting system event observation
Successfully registered for USB notification type: IOServicePublish
USB device change detected
USB device event for: USB Billboard Device   
USB device event for: USB Keyboard
USB device event for: USB 10/100/1000 LAN
USB device event for: USB2.0 Hub
USB device event for: USB Receiver
USB device event for: USB3.1 Hub
USB device event for: USB 2.0 BILLBOARD
USB device event for: USB3.0 Hub             
USB device event for: USB2.0 Hub             
Successfully registered for USB notification type: IOServiceTerminate
USB device change detected
Successfully registered for USB notification type: IOServiceMatched
USB device change detected
USB device event for: USB Billboard Device   
USB device event for: USB Keyboard
USB device event for: USB 10/100/1000 LAN
USB device event for: USB2.0 Hub
USB device event for: USB Receiver
USB device event for: USB3.1 Hub
USB device event for: USB 2.0 BILLBOARD
USB device event for: USB3.0 Hub             
USB device event for: USB2.0 Hub             
Restarting monitoring...
HID Manager closed successfully
Monitoring restarted
HID Manager opened successfully
Currently connected HID devices: 3
Found HID device: Apple Internal Keyboard / Trackpad
Found HID device: USB Receiver
Found HID device: USB Keyboard
change: keyboard changed from nil to USB Keyboard-[1241-17733-unknown-unknown]
Setting input source for keyboard USB Keyboard-[1241-17733-unknown-unknown]: <TSMInputSource 0x6000019ddde0> KB Layout: British – PC (id=250)
change: keyboard changed from USB Keyboard-[1241-17733-unknown-unknown] to Apple Internal Keyboard / Trackpad-[1452-641-Apple Inc.-FM714740HG3N4FTBE+FCM]
Setting input source for keyboard Apple Internal Keyboard / Trackpad-[1452-641-Apple Inc.-FM714740HG3N4FTBE+FCM]: <TSMInputSource 0x6000019ddda0> KB Layout: British (id=2)
change: keyboard changed from Apple Internal Keyboard / Trackpad-[1452-641-Apple Inc.-FM714740HG3N4FTBE+FCM] to USB Keyboard-[1241-17733-unknown-unknown]
Setting input source for keyboard USB Keyboard-[1241-17733-unknown-unknown]: <TSMInputSource 0x6000019ddde0> KB Layout: British – PC (id=250)
USB device change detected
USB device event for: USB 2.0 BILLBOARD
USB device change detected
USB device event for: USB3.0 Hub             
USB device change detected
USB device event for: USB 10/100/1000 LAN
USB device change detected
USB device event for: USB3.1 Hub
USB device change detected
USB device event for: USB2.0 Hub             
USB device change detected
USB device event for: USB Billboard Device   
USB device change detected
USB device event for: USB Receiver
USB device change detected
USB device event for: USB Keyboard
USB device event for: USB2.0 Hub
Restarting monitoring...
HID Manager closed successfully
Monitoring restarted
HID Manager opened successfully
Currently connected HID devices: 1
Found HID device: Apple Internal Keyboard / Trackpad
change: keyboard changed from USB Keyboard-[1241-17733-unknown-unknown] to Apple Internal Keyboard / Trackpad-[1452-641-Apple Inc.-FM714740HG3N4FTBE+FCM]
Setting input source for keyboard Apple Internal Keyboard / Trackpad-[1452-641-Apple Inc.-FM714740HG3N4FTBE+FCM]: <TSMInputSource 0x6000019df7c0> KB Layout: British (id=2)
USB device change detected
USB device event for: USB3.0 Hub             
USB device change detected
USB device event for: USB3.0 Hub             
USB device change detected
USB device event for: USB2.0 Hub             
USB device change detected
USB device event for: USB2.0 Hub             
USB device change detected
USB device event for: USB3.1 Hub
USB device change detected
USB device event for: USB3.1 Hub
USB device change detected
USB device event for: USB Receiver
USB device change detected
USB device event for: USB Receiver
USB device change detected
USB device event for: USB 2.0 BILLBOARD
USB device change detected
USB device event for: USB 2.0 BILLBOARD
USB device change detected
USB device event for: USB2.0 Hub
USB device change detected
USB device event for: USB2.0 Hub
USB device change detected
USB device event for: USB 10/100/1000 LAN
USB device change detected
USB device event for: USB 10/100/1000 LAN
USB device change detected
USB device event for: USB Keyboard
USB device change detected
USB device event for: USB Keyboard
Restarting monitoring...
HID Manager closed successfully
Monitoring restarted
HID Manager opened successfully
Currently connected HID devices: 3
Found HID device: USB Receiver
Found HID device: Apple Internal Keyboard / Trackpad
Found HID device: USB Keyboard
USB device change detected
USB device event for: USB Billboard Device   
USB device change detected
USB device event for: USB Billboard Device   
change: keyboard changed from Apple Internal Keyboard / Trackpad-[1452-641-Apple Inc.-FM714740HG3N4FTBE+FCM] to USB Keyboard-[1241-17733-unknown-unknown]
Setting input source for keyboard USB Keyboard-[1241-17733-unknown-unknown]: <TSMInputSource 0x6000019e8020> KB Layout: British – PC (id=250)
Restarting monitoring...
HID Manager closed successfully
Monitoring restarted
HID Manager opened successfully
Currently connected HID devices: 3
Found HID device: Apple Internal Keyboard / Trackpad
Found HID device: USB Receiver
Found HID device: USB Keyboard
change: keyboard changed from USB Keyboard-[1241-17733-unknown-unknown] to Apple Internal Keyboard / Trackpad-[1452-641-Apple Inc.-FM714740HG3N4FTBE+FCM]
Setting input source for keyboard Apple Internal Keyboard / Trackpad-[1452-641-Apple Inc.-FM714740HG3N4FTBE+FCM]: <TSMInputSource 0x6000019c43a0> KB Layout: British (id=2)
change: keyboard changed from Apple Internal Keyboard / Trackpad-[1452-641-Apple Inc.-FM714740HG3N4FTBE+FCM] to USB Keyboard-[1241-17733-unknown-unknown]
Setting input source for keyboard USB Keyboard-[1241-17733-unknown-unknown]: <TSMInputSource 0x6000019de740> KB Layout: British – PC (id=250)
USB device change detected
USB device event for: USB2.0 Hub             
USB device change detected
USB device event for: USB Billboard Device   
USB device change detected
USB device event for: USB Receiver
USB device change detected
USB device event for: USB 2.0 BILLBOARD
USB device change detected
USB device event for: USB2.0 Hub
USB device change detected
USB device event for: USB Keyboard
USB device change detected
USB device event for: USB3.0 Hub             
USB device change detected
USB device event for: USB3.1 Hub
USB device change detected
USB device event for: USB 10/100/1000 LAN
change: keyboard changed from USB Keyboard-[1241-17733-unknown-unknown] to Apple Internal Keyboard / Trackpad-[1452-641-Apple Inc.-FM714740HG3N4FTBE+FCM]
Setting input source for keyboard Apple Internal Keyboard / Trackpad-[1452-641-Apple Inc.-FM714740HG3N4FTBE+FCM]: <TSMInputSource 0x6000019d4120> KB Layout: British (id=2)
Restarting monitoring...
HID Manager closed successfully
Monitoring restarted
HID Manager opened successfully
Currently connected HID devices: 1
Found HID device: Apple Internal Keyboard / Trackpad
System woke from sleep, restarting monitoring
Restarting monitoring...
HID Manager closed successfully
Monitoring restarted
HID Manager opened successfully
Currently connected HID devices: 1
Found HID device: Apple Internal Keyboard / Trackpad
USB device change detected
USB device event for: USB3.0 Hub             
USB device event for: USB2.0 Hub             
USB device change detected
USB device event for: USB3.0 Hub             
USB device change detected
USB device event for: USB2.0 Hub             
USB device change detected
USB device event for: USB 2.0 BILLBOARD
USB device change detected
USB device event for: USB 2.0 BILLBOARD
USB device change detected
USB device event for: USB3.1 Hub
USB device change detected
USB device event for: USB3.1 Hub
USB device change detected
USB device event for: USB Receiver
USB device change detected
USB device event for: USB Receiver
USB device change detected
USB device event for: USB2.0 Hub
USB device change detected
USB device event for: USB2.0 Hub
USB device change detected
USB device event for: USB 10/100/1000 LAN
USB device change detected
USB device event for: USB 10/100/1000 LAN
USB device change detected
USB device event for: USB Keyboard
USB device change detected
USB device event for: USB Keyboard
Restarting monitoring...
HID Manager closed successfully
Monitoring restarted
HID Manager opened successfully
Currently connected HID devices: 3
Found HID device: USB Receiver
Found HID device: Apple Internal Keyboard / Trackpad
Found HID device: USB Keyboard
USB device change detected
USB device event for: USB Billboard Device   
USB device change detected
USB device event for: USB Billboard Device   
Restarting monitoring...
HID Manager closed successfully
Monitoring restarted
HID Manager opened successfully
Currently connected HID devices: 3
Found HID device: USB Keyboard
Found HID device: USB Receiver
Found HID device: Apple Internal Keyboard / Trackpad



# After wake from sleep, no more keystrokes are acknowledged
```

Weirdly, killing and running the program again in the same terminal, no keystrokes are acknowledged, but we do not see the same HID manager error that we were looking at a few messages up:

```
$ ./.build/release/autokbisw -v 1                                                                                                130 ↵
Starting with useLocation: false - verbosity: 1
HID Manager opened successfully
Currently connected HID devices: 3
Found HID device: Apple Internal Keyboard / Trackpad
Found HID device: USB Keyboard
Found HID device: USB Receiver
Starting system event observation
Successfully registered for USB notification type: IOServicePublish
USB device change detected
USB device event for: USB Billboard Device   
USB device event for: USB Keyboard
USB device event for: USB 10/100/1000 LAN
USB device event for: USB2.0 Hub
USB device event for: USB Receiver
USB device event for: USB3.1 Hub
USB device event for: USB 2.0 BILLBOARD
USB device event for: USB3.0 Hub             
USB device event for: USB2.0 Hub             
Successfully registered for USB notification type: IOServiceTerminate
USB device change detected
Successfully registered for USB notification type: IOServiceMatched
USB device change detected
USB device event for: USB Billboard Device   
USB device event for: USB Keyboard
USB device event for: USB 10/100/1000 LAN
USB device event for: USB2.0 Hub
USB device event for: USB Receiver
USB device event for: USB3.1 Hub
USB device event for: USB 2.0 BILLBOARD
USB device event for: USB3.0 Hub             
USB device event for: USB2.0 Hub             
Restarting monitoring...
HID Manager closed successfully
Monitoring restarted
HID Manager opened successfully
Currently connected HID devices: 3
Found HID device: Apple Internal Keyboard / Trackpad
Found HID device: USB Receiver
Found HID device: USB Keyboard
```

I haven't tried the `tccutil reset InputMonitoring` yet, but I should be able to carve out time for that tomorrow.

> To me, it seems like there's a root issue with permissions on your system that needs to be resolved first

Yep, most likely! I know this is likely an issue with my environment, or more users would be reporting similar issues. Thanks for spending all this time on it!

**Comment by craigfurman** [comment]
`InputMonitoring` doesnt' appear to be a valid argument to tccutil-reset, but `sudo tccutil reset ListenEvent` appears to reset those settings. After reboot, I reconfigured the relevant permissions on prompt, but the same behaviour and similar log pattern as my above message occurred. Sleep appears to be the killer - unplugging and replugging is fine.

I'm totally clueless as to why restarting the program after waking from sleep doesn't fix this. Very odd.

**Comment by ohueter** [comment]
No worries, we've learned a lot while debugging your issue that will make autokbisw more useful and stable for all users in the future! 👍

Regarding your issue, i think we've made progress as well. This here is interesting:

> Weirdly, killing and running the program again in the same terminal, no keystrokes are acknowledged, but we do not see the same HID manager error that we were looking at a few messages up

So permissions seem to be alright now, else the HID manager error would've occurred, right? We need to look elsewhere for the cause.

Could you reproduce this situation, but using trace debugging (`autokbisw -v 2`). After switching stopped working, please hit a few keys on both keyboards , and change the input source using the menu bar switcher. The output will be very crowded, but I'm hoping to see if only no changes to the input source are registered, or if no keystrokes/events are registered at all.

**Comment by craigfurman** [comment]
There is no notable activity with debug log (from the branch build) hitting keys, switching keyboards, or manually toggling input language:

```
$ ./.build/release/autokbisw -v 2                                                                                                                                                                                                                                                                                                                                    130 ↵
Starting with useLocation: false - verbosity: 2
HID Manager opened successfully
Starting UserDefaults observation
Currently connected HID devices: 3
Found HID device: Apple Internal Keyboard / Trackpad
Found HID device: USB Keyboard
Found HID device: USB Receiver
Starting system event observation
Successfully registered for USB notification type: IOServicePublish
USB device change detected
USB device event for: USB Billboard Device   
USB device event for: USB Keyboard
USB device event for: USB 10/100/1000 LAN
USB device event for: USB 2.0 BILLBOARD
USB device event for: USB2.0 Hub
USB device event for: USB Receiver
USB device event for: USB3.1 Hub
USB device event for: USB2.0 Hub             
USB device event for: USB3.0 Hub             
Successfully registered for USB notification type: IOServiceTerminate
USB device change detected
Successfully registered for USB notification type: IOServiceMatched
USB device change detected
USB device event for: USB Billboard Device   
USB device event for: USB Keyboard
USB device event for: USB 10/100/1000 LAN
USB device event for: USB 2.0 BILLBOARD
USB device event for: USB2.0 Hub
USB device event for: USB Receiver
USB device event for: USB3.1 Hub
USB device event for: USB2.0 Hub             
USB device event for: USB3.0 Hub             
Restarting monitoring...
HID Manager closed successfully
Monitoring restarted
HID Manager opened successfully
Starting UserDefaults observation
Currently connected HID devices: 3
Found HID device: Apple Internal Keyboard / Trackpad
Found HID device: USB Receiver
Found HID device: USB Keyboard
```

I started from a state in which no version of autokbisw was working.

It's as if the application's (the terminal in this case) input monitoring permissions are silently revoked, but this isn't reflected in the UI. The problem reliably vanishes after a reboot, and reliably reappears after sleep, on both my laptops.

**Comment by ohueter** [comment]
Thanks for the log, that's very helpful. I think we can exclude the HIDManager for now.

Here's one last thing (for now 😄) that I would like you to do:
1. Bring the system in a state where autokbisw works as expected. Start `./.build/release/autokbisw -v 2` in one Terminal instance.
2. In a second Terminal instance, run e.g. `./.build/release/autokbisw list` and/or `./.build/release/autokbisw enable 1`.
3. There should be a log in Terminal 1 reading 
```
Received settings change notification
Reloaded mappings due to UserDefaults change
```
4. Sleep and wake your laptop.
5. Repeat step 2. Does the `settings change notification` log appear as before sleeping?

Thanks a lot!

In the meantime, I'll update my second laptop to macOS 15 and see if the issue occurs for me as well, and report back :)

**Comment by ohueter** [comment]
I'm sorry to report (well actually I'm quite happy about it 😄) that autokbisw still works as expected on my M1 on macOS 15.2 even after sleeping and waking.

**Comment by craigfurman** [comment]
I rebooted and performed this experiment. I've attached 2 log files

logs-over-sleep.txt is the result of me running the branch build with `-v 2`, then sleeping and waking, and finally running `list` from the branch build. I've annotated the logs with where the wake occurred. We can see the messages you're looking for before and after the sleep.

I rebooted again, and produced logs-over-unplug-and-sleep.txt by unplugging my USB hub, then sleeping, waking, and re-plugging. This reproduced the behaviour in this issue, autokbisw stops working, and we see no log messages when buttons are pressed. I think in this one I forgot to run list before sleeping, but we can still see the expected messages _after_ I ran list after waking.

Thanks again for all your effort so far on this, I know it's a weird one!

[logs-over-sleep.txt](https://github.com/user-attachments/files/18539000/logs-over-sleep.txt)
[logs-over-unplug-and-sleep.txt](https://github.com/user-attachments/files/18539001/logs-over-unplug-and-sleep.txt)

**Comment by ohueter** [comment]
Hi Craig, thanks a lot for the logs. It all seems to work as expected until it doesn't. I'm really out of ideas now.

I pushed yet another version to #48, where I just re-arranged the order of operations in one method and added some more logging. You might want to try that, but I'm not expecting any improvements tbh.

Maybe we should approach the issue from a different angle. You mentioned before:

> The problem reliably vanishes after a reboot, and reliably reappears after sleep, on both my laptops.

So your configuration is MacBook---USB Hub---2 Keyboards, correct? And when you're saying the issue occurs on both of your laptops, you are using the same USB Hub with these same keyboards connected to it, un- und replugging it in either of them?

Could you try to identify the minimal hardware required to reproduce the issue?
- Does the issue occur when only one of the keyboards is connected to the hub? If yes, which one?
- Does the issue occur when not using the USB hub, and plugging in one (or both) keyboard(s) directly?
- Does the issue occur when using a different keyboard model?
- Does the issue occur when using just the internal keyboard, and plugging any other USB device, e.g. a USB memory stick, or a mouse (HID device)?

**Comment by craigfurman** [comment]
To clarify my setup: I have 2 macbooks (1 work, 1 personal), and 2 identical desk setups (long story). At each desk is a keyboard. I have 1 USB hub that connects the keyboards to the mac, that I carry around between the 2 desks. So 2 macs multiplex to 1 of 2 keyboards at a time (never both at the same time), via one USB hub. Now that I describe this, I wish I had another hub to test this on, but sadly I don't at the moment!

For a minimal reproduction, I can observe that `autokbisw -v 2` from main or the branch build from https://github.com/ohueter/autokbisw/pull/48 stops logging keystroke events at all after waking from sleep. 

> Does the issue occur when only one of the keyboards is connected to the hub? If yes, which one?

I only connect one keyboard at a time, and the issue manifests itself with each keyboard.

> Does the issue occur when not using the USB hub, and plugging in one (or both) keyboard(s) directly?

I have no other USB-C -> adapter other than the hub I use. If I get my hands on another one, I'll try an experiment.

> Does the issue occur when using a different keyboard model?

I have only these 2 keyboards. They are technically different models (different generations of the same model) and show up slightly differently in `autobkisw list`.

> Does the issue occur when using just the internal keyboard, and plugging any other USB device, e.g. a USB memory stick, or a mouse (HID device)?

I ran an experiment to try to determine this:

1. Build the latest version of https://github.com/ohueter/autokbisw/pull/48 (`swift build --configuration release`)
2. Disconnect all keyboards and peripherals
3. Reboot
4. Stop the autokbisw service
5. Ensure that my terminal has keyboard monitoring permission
6. `./.build/release/autokbisw -v 2`
7. Press some buttons - observe the events
8. Sleep, wake, press some buttons - observe the events. I repeated this twice, so I think we can tentatively conclude that unplugging and replugging the USB hub is correlated with this issue, since it isn't plugged in yet.
9. Plug in the USB dock with only a keyboard connected (no power, monitor)
10. Press some buttons - observe that events are logged and that autokbisw is switching the keyboard input to the last one associated with that keyboard.
11. Sleep, wake, everything still works!
12. Disconnect USB hub, sleep, wake, reconnect dock, press some buttons: subsequent key events are not logged.
13. Kill the program in the terminal, restart it, press - no key events are logged

Disconnecting my USB hub still somehow appears to be related to this issue. It's incredibly strange how the "event flow stoppage" persists across program restarts. I have no idea what's happening, and must be missing something fundamental.

Logs attached for posterity - we can see the 2 sleeps from the experiment above.

> I'm really out of ideas now.

I don't blame you at all, me too! 😂 
Thanks for sticking with it. If / when I get my hands on more keyboards or USB adapters, I'll see if I can reproduce the issue again. In the mean time, if I had to guess, it must be something unique to the keyboard brand or USB hub, since this manifests across 2 macs but other users haven't been reporting this. I think we can rule out the nix packaging I mentioned above since the experiments and logs I posted here involve running a source-built autokbisw from a terminal, with input monitoring permissions configured for that terminal. That and I get the same issue with the brew service version.

Oh well! Cheers again, I'll post here if new hardware resolves this.

[logs.txt](https://github.com/user-attachments/files/18646624/logs.txt)

**Comment by simonyangme** [comment]
I've been observing what seems like the same issue. I also frequently unplug the USB hub with a mouse and keyboard attached and have the Mac go to sleep as I take my computer away from my desk. Eventually, I no longer see events and won't see them until after a reboot.

**Comment by ohueter** [comment]
Thank you so much for your thorough analysis Craig, I think every software maintainer can only wish for such an engaged user as you are!

Your experiment provided really useful information. Just as you concluded, I think it seems to be a specific issue related to your hardware. I remember reading that a lot of USB devices are not fully spec compliant. Maybe we are hitting an edge case here that messes with macOS's USB stack. A test with a different USB-C dongle and/or a different brand of keyboard would probably be very insightful. That's my best guess at least.

I don't think there's much more I can do at this point. Please report back if you can get your hands on different hardware, and I'll gladly make adjustments to autokbisw if there's anything I can do!

@simonyangme 

> I've been observing what seems like the same issue. I also frequently unplug the USB hub with a mouse and keyboard attached and have the Mac go to sleep as I take my computer away from my desk. Eventually, I no longer see events and won't see them until after a reboot.

Thanks for reporting! There are indeed issues with monitoring across un- and re-plugging USB devices in the current release of autokbisw. If it's within your technical ability, you could compile the code from #48 and see if that version resolves the issue. I need to clean up the code before I can merge the branch and release a new version, which may take some more time.

**Comment by simonyangme** [comment]
I reorganized my desk a week ago and switched out USB keyboards and hubs. I haven't run into the issue since. I was primarily using a ZSA Moonlander plugged into an Anker PowerExpand 8-in-1 USB-C PD hub, and switched to using a ZSA Voyager connected through a Dell U2720Q's USB hub. Both keyboards only ran firmware built and installed using ZSA's web configurator but I'm not sure if they are functionally identical. I wonder if it was an issue caused by the Anker hub. I'll keep monitoring and see if the issue reappears with my new setup.

**Comment by mstarodub** [comment]
Sorry for pinging everyone else in here, but @craigfurman - I came across this issue while looking for a Nix derivation for autokbisw. If you have the bandwidth, I would really appreciate it if you could upstream it (ideally as a home manager service). Thanks in advance!

**Comment by craigfurman** [comment]
@mstarodub I've been meaning to do that for a while now actually, I should get around to that in the next week or so. I'm pretty new to nix, so was sitting on it for a bit to become sure it's stable (and that this issue wasn't due to the nix packaging).

For reference, I package it (https://github.com/craigfurman/nix-workstations/blob/main/pkgs/autokbisw/default.nix) and run it as a darwin service (https://github.com/craigfurman/nix-workstations/blob/main/darwin/autokbisw.nix) in my personal config at the moment.

**Comment by craigfurman** [comment]
@mstarodub, I did start looking at upstreaming my nix packaging for this, but upon reading https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/swift.section.md I tried using the default buildPhase (ensuring the nix swift compiler wrapper is used), and am hitting some build errors when I do that. I want to take the time to understand how swift/macos version targets actually work before proposing the package.

To be clear I only get this issue when I port the package _to nixpkgs_, not in my flake linked above, which is extremely weird to me and reveals that I must be doing something wrong with nix.

I haven't had a ton of time to look deeper into it yet. If I do, I'll open an issue here (since we're well out of scope on this one!) and will be sure to tag you.
